apiVersion: 1
datasources:
  - name: ClickHouse
    type: postgres
    access: proxy
    url: clickhouse:9000
    jsonData:
      database: default
      user: admin
      sslmode: disable
    secureJsonData:
      password: admin123
    isDefault: true
