apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      database: default
      username: admin
      port: 8123
      server: clickhouse
      protocol: http
      tlsSkipVerify: true
    secureJsonData:
      password: admin123
    isDefault: true
