version: 2

models:
  - name: transactions_stg
    description: "Сырые транзакции, очищенные от tombstones"
    columns:
      - name: id
        tests: [not_null]
      - name: user_id
        tests: [not_null]

  - name: user_segments
    description: "Сегментация пользователей по сумме транзакций"
    columns:
      - name: user_id
        tests: [not_null, unique]
      - name: segment
        tests: [not_null]

  - name: daily_revenue
    description: "Дневная выручка по транзакциям"
    columns:
      - name: day
        tests: [not_null, unique]
      - name: daily_revenue
        tests: [not_null]
