server:
  port: 8086

spring:
  application:
    name: kafka-streams-app
  kafka:
    streams:
      bootstrap-servers: ${SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  level:
    org.apache.kafka.streams: INFO
