FROM grafana/grafana:10.2.3

USER root

# Используем новую команду вместо grafana-cli
#RUN grafana cli plugins install vertamedia-clickhouse-datasource || \
#    echo "Failed to install plugin, will try manual installation"

USER grafana 