version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9870" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "9870:9870"
      - "8020:8020"
    environment:
      - CLUSTER_NAME=mycluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./hadoop-config/core-site.xml:/hadoop/etc/hadoop/core-site.xml
      - ./hadoop-config/hdfs-site.xml:/hadoop/etc/hadoop/hdfs-site.xml
    networks:
      - hadoop

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    depends_on:
      - namenode
    environment:
      - CLUSTER_NAME=mycluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
      - ./hadoop-config/core-site.xml:/hadoop/etc/hadoop/core-site.xml
      - ./hadoop-config/hdfs-site.xml:/hadoop/etc/hadoop/hdfs-site.xml
    networks:
      - hadoop

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    depends_on:
      - namenode
    environment:
      - CLUSTER_NAME=mycluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
      - ./hadoop-config/core-site.xml:/hadoop/etc/hadoop/core-site.xml
      - ./hadoop-config/hdfs-site.xml:/hadoop/etc/hadoop/hdfs-site.xml
    networks:
      - hadoop

  hdfs-loader:
    image: bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-loader
    depends_on:
      namenode:
        condition: service_healthy
    environment:
      - CLUSTER_NAME=mycluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HADOOP_CONF_DIR=/hadoop/etc/hadoop
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - hadoop_datanode1:/hadoop/dfs/data
      - hadoop_datanode2:/hadoop/dfs/data
      - ./init:/init
      - ./data:/data
      - ./hadoop-config/core-site.xml:/hadoop/etc/hadoop/core-site.xml
      - ./hadoop-config/hdfs-site.xml:/hadoop/etc/hadoop/hdfs-site.xml
    entrypoint: [ "/bin/bash", "/init/load-hdfs.sh" ]
    networks:
      - hadoop
    restart: "no"

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./hadoop-config/core-site.xml:/opt/spark/conf/core-site.xml
    networks:
      - hadoop
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 10

#  spark-submit-runner:
#    image: apache/spark:3.5.0
#    depends_on:
#      spark-master:
#        condition: service_healthy
#      hdfs-loader:
#        condition: service_completed_successfully
#    volumes:
#      - ./spark-app/build/libs/spark-app-1.0-all.jar:/opt/spark-jars/spark-app-1.0-all.jar
#      - ./spark-master/spark-submit.sh:/opt/spark-app/spark-submit.sh
#      - ./hadoop-config/core-site.xml:/opt/spark/conf/core-site.xml
#    entrypoint: [ "/bin/bash", "-c", "sleep 5 && bash /opt/spark-app/spark-submit.sh" ]
#    networks:
#      - hadoop

  airflow-db:
    image: postgres:15
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data
    networks:
      - hadoop
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
      interval: 10s
      timeout: 5s
      retries: 5

  livy:
    build:
      context: ./livy
      dockerfile: Dockerfile
    container_name: livy
    ports:
      - "8998:8998"
    environment:
      - SPARK_HOME=/opt/spark
    depends_on:
      - spark-master
    volumes:
      - ./spark-app/build/libs/spark-app-1.0-all.jar:/opt/spark-app/spark-app-1.0-all.jar
    networks:
      - hadoop

  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow
    depends_on:
      spark-master:
        condition: service_healthy
      hdfs-loader:
        condition: service_completed_successfully
      airflow-db:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8081:8080"
    command: bash -c "
      airflow db init &&
      airflow db migrate &&
      airflow connections delete livy_default || true &&
      airflow connections add 'livy_default' \
      --conn-type 'http' \
      --conn-host 'http://livy' \
      --conn-port '8998' &&
      airflow users create \
      --username admin \
      --firstname Air \
      --lastname Flow \
      --role Admin \
      --email admin@example.com \
      --password admin &&
      airflow webserver &
      airflow scheduler"
    networks:
      - hadoop

  spark-worker1:
    image: apache/spark:3.5.0
    container_name: spark-worker1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    command: bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    volumes:
      - ./hadoop-config/core-site.xml:/opt/spark/conf/core-site.xml
      - ./spark-app/build/libs/spark-app-1.0-all.jar:/opt/spark-app/spark-app-1.0-all.jar
    depends_on:
      - spark-master
    networks:
      - hadoop

  spark-worker2:
    image: apache/spark:3.5.0
    container_name: spark-worker2
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    command: bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    volumes:
      - ./hadoop-config/core-site.xml:/opt/spark/conf/core-site.xml
      - ./spark-app/build/libs/spark-app-1.0-all.jar:/opt/spark-app/spark-app-1.0-all.jar
    depends_on:
      - spark-master
    networks:
      - hadoop

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  airflow_pgdata:

networks:
  hadoop:
