name: 'fintech_project'
version: '1.0'
profile: 'clickhouse_profile'

on-run-start:
  - '{{ drop_clickhouse_dbt_backups() }}'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  fintech_project:
    staging:
      materialized: view
      tags: ['staging']
    intermediate:
      materialized: view
      tags: ['intermediate']
    dimensions:
      materialized: view
      tags: ['dimensions']
    facts:
      materialized: table
      tags: ['facts']
    marts:
      materialized: table
      tags: ['marts']

seeds:
  fintech_project:
    +full_refresh: true

