clickhouse_profile:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: clickhouse
      port: 8123
      user: admin
      password: admin123
      secure: false
